services:
  # Laravel Backend
  backend:
    #image: amineelhauari/laravel-angular-backend:1.0
    build: ./docker/backend
    container_name: laravel_app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=user
      - DB_PASSWORD=password

  # Angular Frontend
  frontend:
    #image: amineelhauari/laravel-angular-frontend:1.0
    build: ./docker/frontend
    container_name: angular_app
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    depends_on:
      - backend

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
